### ISSUE TITLE
Cannot install next to atflatcontrols

### ISSUE THREAD

**Issue by aducom** [Alexey-T/ATTabs#81] opened 2019-10-29 19:19 UTC
When I install both packages in lazarus I get the error message

The unit atcanvasprimitives exists twice in the unit path of the ide. That is obvious, but how to solve?
How do I merge both packages to avoid this message?

**Comment by srd-software** [comment] 2019-10-29 19:50
Off the top of my head I'd say just rename one of them and try it again.

**Comment by Alexey-T** [comment] 2019-10-29 19:53
I don't merge them here, they are 2 equal units (so CudaText has file copy in ATTabs deleted). not sure i want to rename one of them.

**Comment by srd-software** [comment] 2019-10-29 20:02
Could he adjust the search path in lazarus to avoid the error?

**Comment by Alexey-T** [comment] 2019-10-30 08:09
Okay, so I will split this canvasprimitives to a separate package.

**Comment by aducom** [comment] 2019-10-30 08:23
I think that's a good thing to do. My final solution generated all kind of other mishaps so I abandoned that. Best way for now is renaming or moving all into one directory. Hope to find some time today to do the latest option. Thnx for support.

**Comment by Alexey-T** [comment] 2019-10-30 08:38
https://github.com/Alexey-T/ATCanvasPrimitives

it is now requires by ATTabs and ATFlatControls.
@srd-software Can you please see how to adapt Delphi packages for this? we need new Delphi package in ATCanPri folder too?

**Comment by srd-software** [comment] 2019-10-30 12:58
Alexey, I downloaded all 3 zips (flat controls, tabs and primitives). I created package files for the primitives. I'll do a pull request for that in a minute.

However, keep the following in mind:

Having a dependent package is going to be a little messy for the users as far as delphi component install goes. As far as I know, delphi can't do any fancy (i.e., "conditional" or "multiple") component installs, just one at a time (I confirmed this with a quick web search but you can search as well in case I missed something). So we'll have to tell users in advance (in a readme or something) that they'll have to install the primitives **first**, _then_ they can install either the flat controls and/or tabs.

The only way around this is to either combine your flat controls, attabs and primitives into one package, or to develop a fancy setup program with something like Inno Setup that handles installing either flat controls or attabs (or both) and that install app would take care of installing primitives automatically when needed. That's a fair amount of work as you have to get the user's delphi version, component version(s), and ide paths to install things to. I'd be more inclined to combine everything into one package, but that's just my 2 cents worth.

If you want to stick with what you have now (3 separate packages), note that for ATFlatControls to install without an error when installing it into the delphi ide you need to remove "atcanvasprimitives.pas" from the flat controls package includes list (as it now stands). It will still install with that in there but it throws an error dialog to the user. Easy enough to remove the include reference to fix it.

Oh, one more thing just FYI for you: I'm running delphi 10.3.1 right now. I have 10.3.2 downloaded but I don't plan to install that one unless I run into some big problem with 10.3.1. And I'm not planning on any further updates. I'm retired and I can't justify another $350 (on a fixed income) just to stay current another year! 

This should not be a problem for the time being, but we might run into some issues on down the road if I'm not running the latest delphi ide (and then, only if your controls start accessing or depending on something only in the latest ide). Just something to keep in mind. 

Stan

**Comment by aducom** [comment] 2019-10-30 13:07
From maintenance point of view I would opt for combining packages that use the same code base. I recognize the Delphi standpoint as i quit my asgsqlite components years ago for a similar reason. Or renaming the shared code, but I agree that that's not a very neat solution.

**Comment by srd-software** [comment] 2019-10-30 14:15
I thought about the "misc" tab change as well. I think that would be a good idea.

I love the components. I'm hoping at some point Alexey might add a combobox to the flat controls. I could really use a replacement for the one in delphi.

**Comment by Alexey-T** [comment] 2019-10-30 14:30
Okaaay, I agree that I should combine 3 pks into single FlatControls... todo

**Comment by Alexey-T** [comment] 2019-10-30 19:21
Reason is ATGroups-- its not ready for Delphi, so just don't include ATGroups into Delphi package, but include ATTabs.

**Comment by srd-software** [comment] 2019-10-30 19:54
Yep, that was it. I wrapped any references to groups in the register file with {$ifdef FPC}. That took care of it and it installed OK.

**Comment by Alexey-T** [comment] 2019-10-30 19:56
yes, we need to tell Delphi guys to remove Tabs package and update FlatCon package...

**Comment by srd-software** [comment] 2019-10-30 20:00
OK. Do you want me to do a pull req on the atflatcontrols_register.pas change?

**Comment by srd-software** [comment] 2019-10-30 20:11
Oh, it also was missing a few of the image files in the res folder too. Here are the files in my version of res now. The ones with asterisks were missing in the flat controls download zip:

	tatbutton.bmp
	* tatbuttonstoolbar.bmp
	tatflattoolbar.bmp
	tatgauge.bmp
	tatgroups.bmp
	tatlabellink.bmp
	tatlistbox.bmp
	tatpanelcolor.bmp
	tatpanelsimple.bmp
	* tatscroll.bmp
	tatscrollbar.bmp
	tatstatus.bmp
	tattabs.bmp
	* tgauge.bmp

**Comment by Alexey-T** [comment] 2019-10-30 20:23
They are missing by purpose- I use all files now with the correct component names, Laz can use only them

Yes, pull req

**Comment by srd-software** [comment] 2019-10-30 20:30
Pull req for reg file is in.

I'll try it again once you merge things. I got errors in my ide install for those image files. They may still be referenced in the package. If so I'll fix that and remove them and do another pull req.

**Comment by srd-software** [comment] 2019-10-30 20:35
When I contact delphi for the getit change, would something like the following be OK with you as far as the description goes:

ATFlatControls: A set of custom-drawn controls, independent from OS. Set now includes ATTabs, a Delphi/Lazarus component for lite tabs, OS independent, fully custom drawn. This set includes all the other ATFlatControls: Button, Toolbar, Listbox, ScrollBar, StatusBar, Gauge. They are used/tested in cross-platform text editor CudaText. Supports VCL only.

Feel free to edit if that is not what you would like.

**Comment by Alexey-T** [comment] 2019-10-30 21:01
ATFlatControls description text is good, tks. Yes, pls fix the Delphi icon names, but leave icon files as now (until we don't have nice icons)

**Comment by srd-software** [comment] 2019-10-30 21:22
OK, I did another pull req for the icon changes. That should be it unless you find a problem. If it's OK I'll send an email to the delphi getit guy and get that changed using the new desc above.

**Comment by Alexey-T** [comment] 2019-10-31 05:34
Not yet ok, see my note in the pull req. why not use the new icon files ?

**Comment by Alexey-T** [comment] 2019-10-31 09:44
@srd-software I fixed the icons filenames (w/o testing in Delphi, doing it by hands), pls see

**Comment by srd-software** [comment] 2019-10-31 12:06
Alexey, I downloaded what you have in place now and it seems to be OK. I was able to install it without any issues. Icons all look OK. I see no more reference to the primitives package in the dproj file any more. I removed my repository. I think we can go with what you have now.

**Comment by Alexey-T** [comment] 2019-10-31 12:21
CanvasPrim file should be exposed on ide package. Eg CudaText uses it.

**Comment by srd-software** [comment] 2019-10-31 12:30
You mean it should be registered as a component as well? If so, what name to use? And there's no icon for it, is that OK?

**Comment by Alexey-T** [comment] 2019-10-31 12:38
Not as component- it must be visible to all Delphi code which uses FlatCon- maybe it’s so already ?

**Comment by srd-software** [comment] 2019-10-31 12:44
I removed the old primitive package so it's not on my machine anywhere. And the new flat controls installed OK and didn't complain. I do still have the flat controls folder in my 32 bit library path. As long as that is there anything else should be able to find it. This is all delphi specific, I don't know how lazarus handles it.

**Comment by Alexey-T** [comment] 2019-10-31 12:53
So now all is okay, you can send files to Delphi guys.

**Closed** 2019-10-31 13:20 UTC

**Comment by srd-software** [comment] 2019-10-31 16:10
OK, I sent the update info to Serge at embarcadero. I'll let you know what I hear back.

**Comment by Alexey-T** [comment] 2019-10-31 16:30
Thank you for support!
